import { PrismaClient, Category } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting seed...')

  // Create sample users
  const hashedPassword = await bcrypt.hash('Password123!', 12)

  const alice = await prisma.user.upsert({
    where: { email: 'alice@example.com' },
    update: {},
    create: {
      email: 'alice@example.com',
      password: hashedPassword,
      username: 'alice_eco',
    },
  })

  const bob = await prisma.user.upsert({
    where: { email: 'bob@example.com' },
    update: {},
    create: {
      email: 'bob@example.com',
      password: hashedPassword,
      username: 'bob_green',
    },
  })

  console.log('👥 Created users:', { alice: alice.email, bob: bob.email })

  // Create sample products (prices in INR)
  const products = [
    {
      title: 'Vintage Leather Jacket',
      description: 'Beautiful vintage leather jacket in excellent condition. Perfect for fall and winter. Classic brown color with original brass zippers.',
      category: Category.CLOTHING,
      price: 6500.00,
      imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=400&fit=crop',
      brand: 'Zara',
      condition: 'Excellent',
      size: 'L',
      color: 'Brown',
      material: 'Genuine Leather',
      yearPurchased: 2020,
      yearOfManufacture: 2019,
      location: 'Mumbai',
      quantity: 1,
      originalPackaging: false,
      manualIncluded: false,
      workingCondition: 'Perfect condition, all zippers work smoothly',
      ownerId: alice.id,
    },
    {
      title: 'MacBook Pro 2019',
      description: 'Used MacBook Pro 13" 2019 model. Works perfectly, minor scratches on the lid. Includes original charger and box.',
      category: Category.ELECTRONICS,
      price: 75000.00,
      imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop',
      brand: 'Apple',
      condition: 'Good',
      color: 'Space Gray',
      yearPurchased: 2019,
      yearOfManufacture: 2019,
      location: 'Delhi',
      weight: '1.4 kg',
      dimensions: '30.41 x 21.24 x 1.56 cm',
      quantity: 1,
      originalPackaging: true,
      manualIncluded: true,
      workingCondition: 'Excellent performance, battery health 87%, all ports working',
      ownerId: bob.id,
    },
    {
      title: 'Wooden Coffee Table',
      description: 'Handcrafted wooden coffee table. Solid oak construction, some wear but very sturdy. Perfect for living room.',
      category: Category.FURNITURE,
      price: 12000.00,
      imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=400&fit=crop',
      brand: 'Custom Made',
      condition: 'Good',
      color: 'Natural Wood',
      material: 'Oak Wood',
      yearPurchased: 2021,
      yearOfManufacture: 2021,
      location: 'Bangalore',
      dimensions: '120 x 60 x 45 cm',
      weight: '25 kg',
      quantity: 1,
      originalPackaging: false,
      manualIncluded: false,
      workingCondition: 'Sturdy and stable, minor surface scratches',
      ownerId: alice.id,
    },
    {
      title: 'Programming Books Collection',
      description: 'Collection of 5 programming books including JavaScript, Python, and React guides. All books in excellent condition.',
      category: Category.BOOKS,
      price: 3500.00,
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
      condition: 'Excellent',
      yearPurchased: 2022,
      yearOfManufacture: 2021,
      location: 'Pune',
      weight: '2.5 kg',
      quantity: 5,
      originalPackaging: false,
      manualIncluded: false,
      workingCondition: 'All pages intact, no markings or damage',
      ownerId: bob.id,
    },
    {
      title: 'Designer Handbag',
      description: 'Authentic designer handbag in great condition. Comes with original dust bag and authenticity card.',
      category: Category.ACCESSORIES,
      price: 9500.00,
      imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=400&fit=crop',
      brand: 'Michael Kors',
      condition: 'Excellent',
      color: 'Black',
      material: 'Leather',
      yearPurchased: 2021,
      yearOfManufacture: 2020,
      location: 'Mumbai',
      dimensions: '35 x 25 x 15 cm',
      weight: '0.8 kg',
      quantity: 1,
      originalPackaging: true,
      manualIncluded: true,
      workingCondition: 'All zippers and clasps work perfectly, no wear on handles',
      ownerId: alice.id,
    },
    {
      title: 'Gaming Chair',
      description: 'Ergonomic gaming chair with lumbar support. Black and red design. Adjustable height and armrests.',
      category: Category.FURNITURE,
      price: 15000.00,
      imageUrl: 'https://images.unsplash.com/photo-1541558869434-2840d308329a?w=400&h=400&fit=crop',
      brand: 'DXRacer',
      condition: 'Good',
      color: 'Black/Red',
      material: 'Faux Leather',
      yearPurchased: 2020,
      yearOfManufacture: 2020,
      location: 'Chennai',
      weight: '25 kg',
      dimensions: '70 x 70 x 130 cm',
      quantity: 1,
      originalPackaging: false,
      manualIncluded: true,
      workingCondition: 'All adjustment mechanisms work, minor wear on armrests',
      ownerId: bob.id,
    },
    {
      title: 'iPhone 12',
      description: 'iPhone 12 64GB in blue. Excellent condition, always used with case and screen protector. Battery health 89%.',
      category: Category.ELECTRONICS,
      price: 38000.00,
      imageUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop',
      brand: 'Apple',
      condition: 'Excellent',
      color: 'Blue',
      yearPurchased: 2021,
      yearOfManufacture: 2020,
      location: 'Hyderabad',
      weight: '164g',
      dimensions: '14.67 x 7.15 x 0.74 cm',
      quantity: 1,
      originalPackaging: true,
      manualIncluded: true,
      workingCondition: 'Perfect working condition, battery health 89%, no physical damage',
      ownerId: alice.id,
    },
    {
      title: 'Winter Boots',
      description: 'Waterproof winter boots, size 9. Perfect for hiking and cold weather. Barely used, excellent grip.',
      category: Category.CLOTHING,
      price: 5200.00,
      imageUrl: 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=400&h=400&fit=crop',
      brand: 'Woodland',
      condition: 'Excellent',
      size: '9',
      color: 'Brown',
      material: 'Leather',
      yearPurchased: 2022,
      yearOfManufacture: 2021,
      location: 'Shimla',
      weight: '1.2 kg',
      quantity: 1,
      originalPackaging: true,
      manualIncluded: false,
      workingCondition: 'Excellent grip, waterproof seal intact, minimal wear',
      ownerId: bob.id,
    },
    {
      title: 'Vintage Watch',
      description: 'Classic vintage watch with leather strap. Mechanical movement, keeps perfect time. Serviced recently.',
      category: Category.ACCESSORIES,
      price: 16000.00,
      imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=400&fit=crop',
      brand: 'Titan',
      condition: 'Good',
      color: 'Gold',
      material: 'Stainless Steel',
      yearPurchased: 2018,
      yearOfManufacture: 2017,
      location: 'Kolkata',
      weight: '150g',
      quantity: 1,
      originalPackaging: true,
      manualIncluded: true,
      workingCondition: 'Keeps accurate time, recently serviced, minor scratches on case',
      ownerId: alice.id,
    },
    {
      title: 'Cookbook Collection',
      description: 'Set of 3 popular cookbooks focusing on healthy and sustainable cooking. Includes Indian, Continental, and Asian recipes.',
      category: Category.BOOKS,
      price: 2000.00,
      imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=400&fit=crop',
      condition: 'Good',
      yearPurchased: 2021,
      yearOfManufacture: 2020,
      location: 'Mumbai',
      weight: '1.8 kg',
      quantity: 3,
      originalPackaging: false,
      manualIncluded: false,
      workingCondition: 'All pages intact, some recipe notes in margins',
      ownerId: bob.id,
    },
    // Additional 20+ products
    {
      title: 'Samsung Galaxy S21',
      description: 'Samsung Galaxy S21 5G 128GB in Phantom Gray. Excellent condition with original box and accessories.',
      category: Category.ELECTRONICS,
      price: 32000.00,
      brand: 'Samsung',
      condition: 'Excellent',
      color: 'Phantom Gray',
      yearPurchased: 2021,
      location: 'Bangalore',
      weight: '171g',
      ownerId: alice.id,
    },
    {
      title: 'Nike Air Max Sneakers',
      description: 'Nike Air Max 270 sneakers in size 10. Comfortable and stylish, perfect for daily wear.',
      category: Category.CLOTHING,
      price: 4500.00,
      brand: 'Nike',
      condition: 'Good',
      size: '10',
      color: 'White/Black',
      material: 'Mesh/Rubber',
      yearPurchased: 2021,
      location: 'Delhi',
      ownerId: bob.id,
    },
    {
      title: 'Study Desk with Drawers',
      description: 'Compact study desk with 3 drawers. Perfect for home office or student room. Solid wood construction.',
      category: Category.FURNITURE,
      price: 8500.00,
      brand: 'IKEA',
      condition: 'Good',
      color: 'White',
      material: 'Engineered Wood',
      yearPurchased: 2020,
      location: 'Pune',
      dimensions: '120 x 60 x 75 cm',
      ownerId: alice.id,
    },
    {
      title: 'Canon DSLR Camera',
      description: 'Canon EOS 1500D DSLR camera with 18-55mm lens. Great for photography beginners. Includes camera bag.',
      category: Category.ELECTRONICS,
      price: 28000.00,
      brand: 'Canon',
      condition: 'Excellent',
      color: 'Black',
      yearPurchased: 2020,
      location: 'Chennai',
      weight: '475g',
      ownerId: bob.id,
    },
    {
      title: 'Formal Shirt Collection',
      description: 'Set of 5 formal shirts in various colors. Size M, all in excellent condition. Perfect for office wear.',
      category: Category.CLOTHING,
      price: 3200.00,
      brand: 'Van Heusen',
      condition: 'Excellent',
      size: 'M',
      color: 'Assorted',
      material: 'Cotton',
      yearPurchased: 2021,
      location: 'Mumbai',
      ownerId: alice.id,
    },
    {
      title: 'Bluetooth Headphones',
      description: 'Sony WH-CH720N wireless noise canceling headphones. Excellent sound quality and battery life.',
      category: Category.ELECTRONICS,
      price: 6500.00,
      brand: 'Sony',
      condition: 'Excellent',
      color: 'Black',
      yearPurchased: 2022,
      location: 'Bangalore',
      weight: '192g',
      ownerId: bob.id,
    },
    {
      title: 'Dining Table Set',
      description: '4-seater dining table set with chairs. Solid wood construction, perfect for small families.',
      category: Category.FURNITURE,
      price: 18000.00,
      brand: 'Godrej',
      condition: 'Good',
      color: 'Brown',
      material: 'Teak Wood',
      yearPurchased: 2019,
      location: 'Delhi',
      dimensions: '120 x 80 x 75 cm',
      ownerId: alice.id,
    },
    {
      title: 'Fiction Books Bundle',
      description: 'Collection of 10 bestselling fiction books including thrillers, romance, and mystery novels.',
      category: Category.BOOKS,
      price: 2800.00,
      condition: 'Good',
      yearPurchased: 2020,
      location: 'Kolkata',
      weight: '3.2 kg',
      ownerId: bob.id,
    },
    {
      title: 'Designer Sunglasses',
      description: 'Ray-Ban Aviator sunglasses in gold frame. Classic style, comes with original case and cloth.',
      category: Category.ACCESSORIES,
      price: 4200.00,
      brand: 'Ray-Ban',
      condition: 'Excellent',
      color: 'Gold',
      material: 'Metal/Glass',
      yearPurchased: 2021,
      location: 'Mumbai',
      ownerId: alice.id,
    },
    {
      title: 'Gaming Laptop',
      description: 'ASUS ROG Strix G15 gaming laptop. AMD Ryzen 7, 16GB RAM, RTX 3060. Perfect for gaming and work.',
      category: Category.ELECTRONICS,
      price: 85000.00,
      brand: 'ASUS',
      condition: 'Good',
      color: 'Black',
      yearPurchased: 2021,
      location: 'Hyderabad',
      weight: '2.3 kg',
      ownerId: bob.id,
    },
    {
      title: 'Ethnic Wear Collection',
      description: 'Beautiful collection of 3 ethnic dresses including sarees and salwar suits. Size M, perfect for festivals.',
      category: Category.CLOTHING,
      price: 5500.00,
      condition: 'Excellent',
      size: 'M',
      color: 'Assorted',
      material: 'Silk/Cotton',
      yearPurchased: 2021,
      location: 'Chennai',
      ownerId: alice.id,
    },
    {
      title: 'Office Chair',
      description: 'Ergonomic office chair with mesh back and adjustable height. Perfect for long working hours.',
      category: Category.FURNITURE,
      price: 7500.00,
      brand: 'Featherlite',
      condition: 'Good',
      color: 'Black',
      material: 'Mesh/Plastic',
      yearPurchased: 2020,
      location: 'Bangalore',
      weight: '15 kg',
      ownerId: bob.id,
    },
    {
      title: 'Fitness Tracker',
      description: 'Fitbit Charge 5 fitness tracker with heart rate monitor and GPS. Tracks all your activities.',
      category: Category.ELECTRONICS,
      price: 8500.00,
      brand: 'Fitbit',
      condition: 'Excellent',
      color: 'Black',
      yearPurchased: 2022,
      location: 'Pune',
      weight: '29g',
      ownerId: alice.id,
    },
    {
      title: 'Leather Wallet',
      description: 'Premium leather wallet with multiple card slots and coin pocket. Genuine leather, barely used.',
      category: Category.ACCESSORIES,
      price: 1800.00,
      brand: 'Hidesign',
      condition: 'Excellent',
      color: 'Brown',
      material: 'Genuine Leather',
      yearPurchased: 2022,
      location: 'Delhi',
      ownerId: bob.id,
    },
    {
      title: 'Bookshelf',
      description: '5-tier wooden bookshelf perfect for organizing books and decorative items. Sturdy construction.',
      category: Category.FURNITURE,
      price: 6500.00,
      brand: 'Nilkamal',
      condition: 'Good',
      color: 'Walnut',
      material: 'Engineered Wood',
      yearPurchased: 2020,
      location: 'Mumbai',
      dimensions: '80 x 30 x 180 cm',
      ownerId: alice.id,
    },
    {
      title: 'Tablet with Keyboard',
      description: 'iPad Air 4th Gen 64GB with Magic Keyboard. Perfect for work and entertainment. Includes Apple Pencil.',
      category: Category.ELECTRONICS,
      price: 45000.00,
      brand: 'Apple',
      condition: 'Excellent',
      color: 'Space Gray',
      yearPurchased: 2021,
      location: 'Bangalore',
      weight: '458g',
      ownerId: bob.id,
    },
    {
      title: 'Winter Jacket',
      description: 'Warm winter jacket with hood. Water-resistant and perfect for cold weather. Size L.',
      category: Category.CLOTHING,
      price: 3800.00,
      brand: 'Decathlon',
      condition: 'Good',
      size: 'L',
      color: 'Navy Blue',
      material: 'Polyester',
      yearPurchased: 2021,
      location: 'Delhi',
      ownerId: alice.id,
    },
    {
      title: 'Smart TV',
      description: '43-inch Smart LED TV with 4K resolution. Android TV with built-in WiFi and streaming apps.',
      category: Category.ELECTRONICS,
      price: 25000.00,
      brand: 'Mi',
      condition: 'Excellent',
      color: 'Black',
      yearPurchased: 2021,
      location: 'Chennai',
      weight: '8.5 kg',
      dimensions: '96.3 x 55.7 x 8.5 cm',
      ownerId: bob.id,
    },
    {
      title: 'Designer Backpack',
      description: 'Stylish laptop backpack with multiple compartments. Perfect for college or office use.',
      category: Category.ACCESSORIES,
      price: 2500.00,
      brand: 'Wildcraft',
      condition: 'Good',
      color: 'Black/Gray',
      material: 'Nylon',
      yearPurchased: 2021,
      location: 'Pune',
      ownerId: alice.id,
    },
    {
      title: 'Sofa Set',
      description: '3+2 seater sofa set in excellent condition. Comfortable and stylish, perfect for living room.',
      category: Category.FURNITURE,
      price: 35000.00,
      brand: 'Urban Ladder',
      condition: 'Excellent',
      color: 'Beige',
      material: 'Fabric',
      yearPurchased: 2020,
      location: 'Mumbai',
      dimensions: '200 x 90 x 85 cm',
      ownerId: bob.id,
    },
  ]

  for (const productData of products) {
    await prisma.product.create({
      data: {
        ...productData,
        status: 'Available'
      },
    })
  }

  console.log('📦 Created sample products')

  // Create a sample cart item for Alice
  const bobProducts = await prisma.product.findMany({
    where: { ownerId: bob.id },
    take: 2,
  })

  if (bobProducts.length > 0) {
    await prisma.cartItem.create({
      data: {
        userId: alice.id,
        productId: bobProducts[0].id,
        quantity: 1,
      },
    })
    console.log('🛒 Created sample cart item')
  }

  console.log('✅ Seed completed successfully!')
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
